#!/bin/sh

: << =cut

=head1 NAME

Process memory - Plugin to measure process memory usage.

=cut

get_memory_usage()
{
  keyword=$1
  sum=0
  for pid in $(pgrep -i "$keyword")
  do
    sum=$((sum+$(ps -o rss= -p "$pid")*1024))
  done
  echo $sum;
  return
}

process=${0##*/proc_mem_}

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo "graph_title $process Memory Usage"
        echo 'graph_vlabel Bytes'
        echo 'graph_args --base 1024 -l 0'
        echo 'graph_category proc_memory'
        echo 'mem.label memory'
        echo 'mem.draw AREA'
        exit 0
fi

echo "mem.value $(get_memory_usage "$process")"